spring:
  application:
    name: costume-recommender-be

  datasource:
    url: jdbc:mysql://localhost:3306/recommender_db
    username: recommender
    password: halloween
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

